name: run autotests


on:
  workflow_dispatch:
  inputs:
  deployment_target:
  description: select test to run
  required: true
  type: choice
  default: all
  options:
    -all

jobs:
run-tests:
  run-on: ubuntu-latest
  name: tests
  steps: 
    - name: Copy sourse code
    users: actions/checkout@v4
    - name: Set up Python env
    users: actions/setup-python@v5
    with:
       python-version: "3.10"
    - name: install dependencies
    run: pip install  -r requirements.txt
    - name: Run test
    run: pytest -v
