name: CI/CD Pipeline  # Название workflow

on:  # Триггеры (когда запускать)
  push:
    branches: [ "main" ]  # Только при пуше в main
  pull_request:
    branches: [ "main" ]  # И при PR в main

jobs:  # Задачи (может быть несколько)
  build-and-test:  # Название задачи
    runs-on: ubuntu-latest  # ОС для запуска

    steps:  # Шаги выполнения
      - name: Checkout code  # Шаг 1: Клонируем репозиторий
        uses: actions/checkout@v3

      - name: Set up Python  # Шаг 2: Устанавливаем Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies  # Шаг 3: Устанавливаем зависимости
        run: |
          pip install -r requirements.txt

      - name: Run tests  # Шаг 4: Запускаем тесты
        run: |
          pytest tests/
      
      - name: Deploy to AWS S3  # Шаг 5: Деплой
        if: github.ref == 'refs/heads/main'  # Только при пуше в main
        run: |
          aws s3 sync ./dist s3://my-bucket/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      
